### ISSUE TITLE
Add email verification to register user process

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum#18]
- [ ] After a user creates an account, a verification email is sent to his email address.
- [ ] Email includes activation token. 
- [ ] A user can only log in after he clicks on the verification link.
- [ ] If a user has not activated the account and tries to log in he can resend an activation email

Token:

- [ ] Activation token is stored hashed in a database.
- [ ] Token has a expiry date.

**Comment by likt0r** [comment]
https://github.com/mailhog/MailHog
For local development and testing of email sending

**Comment by lcatania** [comment]
Hi iam Lorenzo, 
because of the current public exposure of corrective , i stumbled over this project and wanted to help in some way. 

I read that you are planning on using vue so to have fancy emails you could think about using [Vue-email](https://vuemail.net/) its a nuxt compatible package and also can be implmented in express like environments. If i have some time this week i could source a fork with a sample implementation of what is described in the issue by @likt0r

**Comment by likt0r** [comment]
Hi Lorenzo,

My apologies for the late response. It's great to hear that you're interested in joining our project! Your work on VueEmail caught my eye, and it's particularly exciting since we use Nuxt in our frontend. We'll be opening up the Frontend repository to the public shortly, and I'm excited to see your contributions through a merge request.

Best,

Benjamin

**Comment by lcatania** [comment]
Dont worry about the respomse time :)

I didnt quite understand the structure of this project. From the code it looks like this repo is the backend of the project. And i assumed there will be some sort of frontend. Nuxt itself has a "server" layer to handle database access, auth etc. 

If you plan to handle the verification process from here (this repo) then vue-email maybe is not the right fit . 

Best

Lorenzo

**Comment by likt0r** [comment]
Hi Lorenzo,

Yes, you're correct – this is indeed the backend portion. As for the frontend, we're utilizing a Nuxt app. Our backend is structured with TS.ed, which essentially is a typed, class-based framework built around Express. Integrating vue-email would introduce some additional dependencies, but i like the idea of having vue based email templates. 

Best

Benjamin
