### ISSUE TITLE
Add CMS for Knowlegebase

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum#79]
* Linkliste
* Onepage

**Comment by CaLi-Correctiv** [comment]
Which content on the knowledge base / Wissenssammlung:

- Intro slide-show to explain workflow and functionalities on Faktenforum platform
- one pagers produced in the project; maybe with preview or as articles; link collection to each one pager
- selected videos from Reporterfabrik and GADMO relevant to fact-checking (they are in Youtube)
- quiz once we have introduced it to newsletter
- chatbot Abfragefenster
- Netiquette: how to play along in Faktenforum
